spring.application.name=EventManager

spring.data.mongodb.uri=mongodb+srv://giuseppe_db_user:123@cluster0.lfnesef.mongodb.net/UniPlan?retryWrites=true&w=majority&appName=Cluster0

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-small-morning-apm9h3z9.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_so8QyeYn4Pmp
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

server.port=8081
spring.data.mongodb.database=UniPlan
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=DEBUG