# MongoDB (DBA)
spring.data.mongodb.uri=mongodb+srv://giuseppe_db_user:123@cluster0.lfnesef.mongodb.net/UniPlan?retryWrites=true&w=majority&appName=Cluster0

# PostgreSQL (DBA)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.ubvbsawipfepclxdvglm
spring.datasource.password=2UsnTWpSPIj9L6J0
spring.datasource.driver-class-name=org.postgresql.Driver
